# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'show.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow


class Ui_MainWindow(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(944, 536)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.showWidget = QtWidgets.QLabel(self.centralwidget)
        self.showWidget.setGeometry(QtCore.QRect(30, 30, 640, 480))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showWidget.sizePolicy().hasHeightForWidth())
        self.showWidget.setSizePolicy(sizePolicy)
        self.showWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.showWidget.setStyleSheet("background-color: rgb(204, 204, 204);\n"
                                      "font: 14pt \"Adobe Devanagari\";")
        self.showWidget.setAlignment(QtCore.Qt.AlignCenter)
        self.showWidget.setObjectName("showWidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(730, 20, 171, 31))
        self.label.setStyleSheet("font: 75 15pt \"微软雅黑\";")
        self.label.setObjectName("label")
        self.statementLabel = QtWidgets.QLabel(self.centralwidget)
        self.statementLabel.setGeometry(QtCore.QRect(700, 340, 221, 71))
        self.statementLabel.setStyleSheet("font: 75 14pt \"微软雅黑\";\n"
                                          "background-color: rgba(255, 255, 127, 80);")
        self.statementLabel.setText("")
        self.statementLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statementLabel.setObjectName("statementLabel")
        self.resultWidget = QtWidgets.QLabel(self.centralwidget)
        self.resultWidget.setGeometry(QtCore.QRect(700, 60, 221, 271))
        # 右侧结果框,字体样式表
        self.resultWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                        "font: 10pt \"Times New Roman\";\n"
                                        "border-color: rgb(106, 106, 106);\n"
                                        "\n"
                                        "border-width:1px;\n"
                                        "border-style: solid;")
        self.resultWidget.setObjectName("resultWidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(700, 430, 111, 41))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                      "border-color: rgb(0, 125, 170);\n"
                                      "font: 18pt \"微软雅黑\";\n"
                                      "color: rgb(0, 125, 170);\n"
                                      "border-radius: 10px;  border: 2px  rgb(0, 125, 170);\n"
                                      "border-style: outset;")
        self.pushButton.setObjectName("pushButton")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(820, 430, 100, 100))
        self.image.setStyleSheet("background-color: rgb(204, 204, 204);\n"
                                 "font: 14pt \"Adobe Devanagari\";")
        self.image.setObjectName("image")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(700, 480, 111, 41))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                        "\n"
                                        "font: 16pt \"微软雅黑\";\n"
                                        "color: rgb(170, 0, 0);\n"
                                        "border-radius: 10px;  border: 2px  rgb(170, 0, 0);\n"
                                        "border-style: outset;")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.showWidget.setWhatsThis(_translate("MainWindow", "show picture"))
        self.showWidget.setText(_translate("MainWindow", "图像显示"))
        self.label.setText(_translate("MainWindow", "识别结果输出区"))
        self.resultWidget.setText(_translate("MainWindow", "结果显示"))
        self.pushButton.setText(_translate("MainWindow", "&Start"))
        self.pushButton_2.setText(_translate("MainWindow", "Close"))

        # import UI.res_rc
        MainWindow.show()
